apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: file-writer
  name: file-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: file-writer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: file-writer
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
            - name: AZURE_SQL_CONNECTION_STRING
              value: Driver={ODBC Driver 18 for SQL Server};Server=dash-gtd.database.windows.net;Database=us_stock_options_db;Uid=dash_gtd;Pwd=wearethebest@69;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=60;
            - name: S3_BUCKET_NAME
              value: dash-gtd-us-east-1-processed-data
          image: file-writer
          name: file-writer
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
              protocol: TCP
          volumeMounts:
            - mountPath: /app/daily_exports
              name: file-writer-claim0
      restartPolicy: Always
      volumes:
        - name: file-writer-claim0
          persistentVolumeClaim:
            claimName: file-writer-claim0
